
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Aug 25 22:27:16 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 22;
  public static final int CHAR = 39;
  public static final int CONST = 35;
  public static final int GEQUAL = 27;
  public static final int LPAREN = 6;
  public static final int GREATER = 26;
  public static final int SEMI = 5;
  public static final int INT = 36;
  public static final int LESS = 28;
  public static final int MINUS = 18;
  public static final int RPAREN = 7;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int BOOL = 38;
  public static final int COMMA = 10;
  public static final int DIV = 20;
  public static final int PLUS = 9;
  public static final int ASSIGN = 32;
  public static final int MAIN = 14;
  public static final int LSQBRACE = 15;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 23;
  public static final int RETURN = 8;
  public static final int EQUAL = 24;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int MOD = 21;
  public static final int IDENT = 37;
  public static final int VOID = 13;
  public static final int COLON = 33;
  public static final int LBRACE = 3;
  public static final int LEQUAL = 29;
  public static final int READ = 12;
  public static final int NEQUAL = 25;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int RSQBRACE = 16;
  public static final int PRINT = 11;
}

